main_project_blog/models.py
from main_project_blog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)



class User(db.Model, UserMixin):
    
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)
    profile_image = db.Column(db.String(64),nullable=False,default='default_profile_picture.png')

    email = db.Column(db.String(30),unique=True,index=True)
    username = db.Column(db.String(15),unique=True,index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost',backref='author',lazy=True)


    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f"Username: {self.username}"




class BlogPost(db.Model):
    
    users = db.relationship(User)

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    post_image = db.Column(db.String(120),nullable=False,default='default_post_picture.png')

    date = db.Column(db.DateTime,nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(150),nullable=False)
    text = db.Column(db.Text,nullable=False)


    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} -- Date: {self.date} -- Title: {self.title}"

main_project_blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email, EqualTo
from flask_wtf.file import _FileField, FileAllowed, FileField
from flask_login import current_user
from main_project_blog.models import User


class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log In')



class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])
    submit = SubmitField('Register')


    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered!')


    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already registered!')



class UpdateUserForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg','png','jpeg'])])
    submit = SubmitField('Update Profile')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered!')


    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already registered!')

main_project_blog/__init__.py
#Main_Project_Blog init
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager, login_manager
import os


app = Flask(__name__)

##############
###DB Setup###
##############

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)


###################
###Login Manager###
###################
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'



################
###Blueprints###
################

from main_project_blog.core.views import core
from main_project_blog.error_pages.handlers import error_pages

app.register_blueprint(core)
app.register_blueprint(error_pages)

main_project_blog/core/views.py
#Core views
from flask import render_template, request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

main_project_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock  %}</title> 
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('core.index')}}">
                <img src="../static/icono-pina-home.png" alt="" width="25" height="29" class="d-inline-block align-text-top">
                Blog
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">

              <a class="nav-link" href="{{url_for('core.info')}}">About</a>

              <a class="nav-link" href="{{url_for('core.index')}}">Create a Post</a>
              <a class="nav-link" href="{{url_for('core.index')}}">Account</a>
              <a class="nav-link" href="{{url_for('core.index')}}">Log out</a>

              <a class="nav-link" href="{{url_for('core.index')}}">Log In</a>
              <a class="nav-link" href="{{url_for('core.index')}}">Register</a>
            </div>
          </div>
        </div>
      </nav>

      <div class="container">
          {% block content %}
          
          {% endblock  %}

      </div>

</body>
</html>

main_project_blog/templates/index.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock  %}

{% block content %}
<div class="bg-light p-5 rounded-lg m-3">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
{% endblock  %}

main_project_blog/templates/info.html
{% extends "base.html" %}

{% block content %}
<div class="bg-light p-5 rounded-lg m-3">
  <h1 class="display-4">Info</h1>
  <hr class="my-4">
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident quae sapiente ipsa non rerum temporibus odio, officiis aspernatur quos possimus tempore cumque suscipit sequi, sunt voluptatibus, aliquam impedit optio placeat?</p>
  
</div>
{% endblock  %}